// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rip_rpc_itf/rip_rpc_itf.proto

package rip_rpc_itf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Login_DoLogin_Prm struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pswd                 string   `protobuf:"bytes,2,opt,name=pswd,proto3" json:"pswd,omitempty"`
	Code                 int64    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_DoLogin_Prm) Reset()         { *m = Login_DoLogin_Prm{} }
func (m *Login_DoLogin_Prm) String() string { return proto.CompactTextString(m) }
func (*Login_DoLogin_Prm) ProtoMessage()    {}
func (*Login_DoLogin_Prm) Descriptor() ([]byte, []int) {
	return fileDescriptor_c37b526ac8044dd4, []int{0}
}

func (m *Login_DoLogin_Prm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_DoLogin_Prm.Unmarshal(m, b)
}
func (m *Login_DoLogin_Prm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_DoLogin_Prm.Marshal(b, m, deterministic)
}
func (m *Login_DoLogin_Prm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_DoLogin_Prm.Merge(m, src)
}
func (m *Login_DoLogin_Prm) XXX_Size() int {
	return xxx_messageInfo_Login_DoLogin_Prm.Size(m)
}
func (m *Login_DoLogin_Prm) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_DoLogin_Prm.DiscardUnknown(m)
}

var xxx_messageInfo_Login_DoLogin_Prm proto.InternalMessageInfo

func (m *Login_DoLogin_Prm) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Login_DoLogin_Prm) GetPswd() string {
	if m != nil {
		return m.Pswd
	}
	return ""
}

func (m *Login_DoLogin_Prm) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Login_DoLogin_Ret struct {
	P0                   bool     `protobuf:"varint,1,opt,name=p0,proto3" json:"p0,omitempty"`
	P1                   int64    `protobuf:"varint,2,opt,name=p1,proto3" json:"p1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_DoLogin_Ret) Reset()         { *m = Login_DoLogin_Ret{} }
func (m *Login_DoLogin_Ret) String() string { return proto.CompactTextString(m) }
func (*Login_DoLogin_Ret) ProtoMessage()    {}
func (*Login_DoLogin_Ret) Descriptor() ([]byte, []int) {
	return fileDescriptor_c37b526ac8044dd4, []int{1}
}

func (m *Login_DoLogin_Ret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_DoLogin_Ret.Unmarshal(m, b)
}
func (m *Login_DoLogin_Ret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_DoLogin_Ret.Marshal(b, m, deterministic)
}
func (m *Login_DoLogin_Ret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_DoLogin_Ret.Merge(m, src)
}
func (m *Login_DoLogin_Ret) XXX_Size() int {
	return xxx_messageInfo_Login_DoLogin_Ret.Size(m)
}
func (m *Login_DoLogin_Ret) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_DoLogin_Ret.DiscardUnknown(m)
}

var xxx_messageInfo_Login_DoLogin_Ret proto.InternalMessageInfo

func (m *Login_DoLogin_Ret) GetP0() bool {
	if m != nil {
		return m.P0
	}
	return false
}

func (m *Login_DoLogin_Ret) GetP1() int64 {
	if m != nil {
		return m.P1
	}
	return 0
}

type Login_Test1_Prm struct {
	A                    []string `protobuf:"bytes,1,rep,name=a,proto3" json:"a,omitempty"`
	B                    []int64  `protobuf:"varint,2,rep,packed,name=b,proto3" json:"b,omitempty"`
	C                    []uint64 `protobuf:"varint,3,rep,packed,name=c,proto3" json:"c,omitempty"`
	D                    []uint64 `protobuf:"varint,4,rep,packed,name=d,proto3" json:"d,omitempty"`
	E                    []int32  `protobuf:"varint,5,rep,packed,name=e,proto3" json:"e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_Test1_Prm) Reset()         { *m = Login_Test1_Prm{} }
func (m *Login_Test1_Prm) String() string { return proto.CompactTextString(m) }
func (*Login_Test1_Prm) ProtoMessage()    {}
func (*Login_Test1_Prm) Descriptor() ([]byte, []int) {
	return fileDescriptor_c37b526ac8044dd4, []int{2}
}

func (m *Login_Test1_Prm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_Test1_Prm.Unmarshal(m, b)
}
func (m *Login_Test1_Prm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_Test1_Prm.Marshal(b, m, deterministic)
}
func (m *Login_Test1_Prm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_Test1_Prm.Merge(m, src)
}
func (m *Login_Test1_Prm) XXX_Size() int {
	return xxx_messageInfo_Login_Test1_Prm.Size(m)
}
func (m *Login_Test1_Prm) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_Test1_Prm.DiscardUnknown(m)
}

var xxx_messageInfo_Login_Test1_Prm proto.InternalMessageInfo

func (m *Login_Test1_Prm) GetA() []string {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *Login_Test1_Prm) GetB() []int64 {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *Login_Test1_Prm) GetC() []uint64 {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *Login_Test1_Prm) GetD() []uint64 {
	if m != nil {
		return m.D
	}
	return nil
}

func (m *Login_Test1_Prm) GetE() []int32 {
	if m != nil {
		return m.E
	}
	return nil
}

type Login_Test1_Ret struct {
	P0                   []int64  `protobuf:"varint,1,rep,packed,name=p0,proto3" json:"p0,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_Test1_Ret) Reset()         { *m = Login_Test1_Ret{} }
func (m *Login_Test1_Ret) String() string { return proto.CompactTextString(m) }
func (*Login_Test1_Ret) ProtoMessage()    {}
func (*Login_Test1_Ret) Descriptor() ([]byte, []int) {
	return fileDescriptor_c37b526ac8044dd4, []int{3}
}

func (m *Login_Test1_Ret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_Test1_Ret.Unmarshal(m, b)
}
func (m *Login_Test1_Ret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_Test1_Ret.Marshal(b, m, deterministic)
}
func (m *Login_Test1_Ret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_Test1_Ret.Merge(m, src)
}
func (m *Login_Test1_Ret) XXX_Size() int {
	return xxx_messageInfo_Login_Test1_Ret.Size(m)
}
func (m *Login_Test1_Ret) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_Test1_Ret.DiscardUnknown(m)
}

var xxx_messageInfo_Login_Test1_Ret proto.InternalMessageInfo

func (m *Login_Test1_Ret) GetP0() []int64 {
	if m != nil {
		return m.P0
	}
	return nil
}

type Login_Test2_Prm struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_Test2_Prm) Reset()         { *m = Login_Test2_Prm{} }
func (m *Login_Test2_Prm) String() string { return proto.CompactTextString(m) }
func (*Login_Test2_Prm) ProtoMessage()    {}
func (*Login_Test2_Prm) Descriptor() ([]byte, []int) {
	return fileDescriptor_c37b526ac8044dd4, []int{4}
}

func (m *Login_Test2_Prm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_Test2_Prm.Unmarshal(m, b)
}
func (m *Login_Test2_Prm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_Test2_Prm.Marshal(b, m, deterministic)
}
func (m *Login_Test2_Prm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_Test2_Prm.Merge(m, src)
}
func (m *Login_Test2_Prm) XXX_Size() int {
	return xxx_messageInfo_Login_Test2_Prm.Size(m)
}
func (m *Login_Test2_Prm) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_Test2_Prm.DiscardUnknown(m)
}

var xxx_messageInfo_Login_Test2_Prm proto.InternalMessageInfo

func (m *Login_Test2_Prm) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Login_Test2_Ret struct {
	P0                   bool     `protobuf:"varint,1,opt,name=p0,proto3" json:"p0,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_Test2_Ret) Reset()         { *m = Login_Test2_Ret{} }
func (m *Login_Test2_Ret) String() string { return proto.CompactTextString(m) }
func (*Login_Test2_Ret) ProtoMessage()    {}
func (*Login_Test2_Ret) Descriptor() ([]byte, []int) {
	return fileDescriptor_c37b526ac8044dd4, []int{5}
}

func (m *Login_Test2_Ret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_Test2_Ret.Unmarshal(m, b)
}
func (m *Login_Test2_Ret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_Test2_Ret.Marshal(b, m, deterministic)
}
func (m *Login_Test2_Ret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_Test2_Ret.Merge(m, src)
}
func (m *Login_Test2_Ret) XXX_Size() int {
	return xxx_messageInfo_Login_Test2_Ret.Size(m)
}
func (m *Login_Test2_Ret) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_Test2_Ret.DiscardUnknown(m)
}

var xxx_messageInfo_Login_Test2_Ret proto.InternalMessageInfo

func (m *Login_Test2_Ret) GetP0() bool {
	if m != nil {
		return m.P0
	}
	return false
}

func init() {
	proto.RegisterType((*Login_DoLogin_Prm)(nil), "rip_rpc_itf.Login_DoLogin_Prm")
	proto.RegisterType((*Login_DoLogin_Ret)(nil), "rip_rpc_itf.Login_DoLogin_Ret")
	proto.RegisterType((*Login_Test1_Prm)(nil), "rip_rpc_itf.Login_Test1_Prm")
	proto.RegisterType((*Login_Test1_Ret)(nil), "rip_rpc_itf.Login_Test1_Ret")
	proto.RegisterType((*Login_Test2_Prm)(nil), "rip_rpc_itf.Login_Test2_Prm")
	proto.RegisterType((*Login_Test2_Ret)(nil), "rip_rpc_itf.Login_Test2_Ret")
}

func init() { proto.RegisterFile("rip_rpc_itf/rip_rpc_itf.proto", fileDescriptor_c37b526ac8044dd4) }

var fileDescriptor_c37b526ac8044dd4 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x99, 0x4c, 0x57, 0xdc, 0x28, 0xfe, 0xe9, 0x29, 0x17, 0x21, 0xc6, 0x4b, 0x4e, 0xda,
	0xee, 0x7e, 0x05, 0x8f, 0x82, 0x32, 0x08, 0x1e, 0xcb, 0xb6, 0x8d, 0x52, 0x44, 0x13, 0xd2, 0x8a,
	0xf8, 0xed, 0x65, 0xa6, 0x1e, 0xba, 0xb2, 0xa7, 0xbc, 0xdf, 0x63, 0x78, 0x33, 0x2f, 0xfa, 0x2a,
	0x0f, 0xa9, 0xc9, 0xa9, 0x6b, 0x86, 0xe9, 0xf5, 0x6e, 0xa1, 0x6f, 0x53, 0x8e, 0x53, 0x2c, 0x4f,
	0x16, 0x96, 0x7b, 0xd4, 0x97, 0x0f, 0xf1, 0x6d, 0xf8, 0x6c, 0xee, 0xe3, 0xfc, 0x3e, 0xe5, 0x8f,
	0xb2, 0xd4, 0xc5, 0xd7, 0x18, 0xb2, 0x01, 0x0b, 0x7e, 0x4d, 0xa2, 0xd9, 0x4b, 0xe3, 0x77, 0x6f,
	0xd4, 0xec, 0xb1, 0x66, 0xaf, 0x8b, 0x7d, 0x30, 0x68, 0xc1, 0x23, 0x89, 0x76, 0xdb, 0xff, 0x81,
	0x14, 0xa6, 0xf2, 0x4c, 0xab, 0x54, 0x49, 0xdc, 0x31, 0xa9, 0x54, 0x09, 0xd7, 0x12, 0x85, 0xa4,
	0x52, 0xed, 0x5e, 0xf4, 0xf9, 0x3c, 0xfc, 0x1c, 0xc6, 0xa9, 0x96, 0x1b, 0x4e, 0x35, 0xec, 0x0c,
	0x58, 0xf4, 0x6b, 0x82, 0x1d, 0x53, 0x6b, 0x94, 0x45, 0x8f, 0x04, 0x2d, 0x53, 0x67, 0xd0, 0xa2,
	0x2f, 0x08, 0x3a, 0xa6, 0xde, 0x14, 0x33, 0xf5, 0x4c, 0xc1, 0xac, 0x2c, 0xfa, 0x15, 0x41, 0x70,
	0xd7, 0xfb, 0xc1, 0xcb, 0x5b, 0x50, 0x76, 0x57, 0xee, 0x66, 0x39, 0xb2, 0x91, 0xdd, 0x17, 0x1a,
	0xdf, 0xc3, 0xcf, 0x5f, 0x7d, 0x96, 0xfb, 0x39, 0x9b, 0x43, 0x9d, 0xda, 0x23, 0xf9, 0xdd, 0xed,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xc6, 0x5d, 0x2f, 0x7e, 0x01, 0x00, 0x00,
}
