// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/base.proto

/*
Package base is a generated protocol buffer package.

It is generated from these files:
	base/base.proto

It has these top-level messages:
	Call
	Ret
*/
package base

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import dict "pb/dict"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Call struct {
	Dict dict.EDict `protobuf:"varint,1,opt,name=dict,enum=dict.EDict" json:"dict,omitempty"`
	Msg  []byte     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *Call) Reset()                    { *m = Call{} }
func (m *Call) String() string            { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()               {}
func (*Call) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Call) GetDict() dict.EDict {
	if m != nil {
		return m.Dict
	}
	return dict.EDict_None
}

func (m *Call) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Ret struct {
	Dict dict.EDict `protobuf:"varint,1,opt,name=dict,enum=dict.EDict" json:"dict,omitempty"`
	Err  bool       `protobuf:"varint,2,opt,name=Err" json:"Err,omitempty"`
	Msg  []byte     `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *Ret) Reset()                    { *m = Ret{} }
func (m *Ret) String() string            { return proto.CompactTextString(m) }
func (*Ret) ProtoMessage()               {}
func (*Ret) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Ret) GetDict() dict.EDict {
	if m != nil {
		return m.Dict
	}
	return dict.EDict_None
}

func (m *Ret) GetErr() bool {
	if m != nil {
		return m.Err
	}
	return false
}

func (m *Ret) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*Call)(nil), "base.Call")
	proto.RegisterType((*Ret)(nil), "base.Ret")
}

func init() { proto.RegisterFile("base/base.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4a, 0x2c, 0x4e,
	0xd5, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x94, 0x50, 0x41,
	0x92, 0x7e, 0x4a, 0x66, 0x72, 0x09, 0x98, 0x80, 0xc8, 0x28, 0xe9, 0x71, 0xb1, 0x38, 0x27, 0xe6,
	0xe4, 0x08, 0x49, 0x72, 0xb1, 0x80, 0x44, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0xb8, 0xf5,
	0xc0, 0x4a, 0x5c, 0x5d, 0x32, 0x93, 0x4b, 0x84, 0xb8, 0xb9, 0x98, 0x73, 0x8b, 0xd3, 0x25, 0x98,
	0x14, 0x18, 0x35, 0x78, 0x94, 0xac, 0xb8, 0x98, 0x83, 0x52, 0x4b, 0x08, 0x28, 0x77, 0x2d, 0x2a,
	0x02, 0x2b, 0xe7, 0x80, 0xe9, 0x65, 0x06, 0xe9, 0x4d, 0x62, 0x03, 0x5b, 0x69, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xaa, 0xce, 0x6b, 0xa4, 0x9f, 0x00, 0x00, 0x00,
}
