// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dict.proto

/*
Package dict is a generated protocol buffer package.

It is generated from these files:
	dict.proto

It has these top-level messages:
*/
package dict

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EDict int32

const (
	EDict_None                          EDict = 0
	EDict_base_Call                     EDict = 1
	EDict_rip_rpc_itf_Login_DoLogin_Ret EDict = 2
	EDict_rip_rpc_itf_Login_Test1_Ret   EDict = 3
	EDict_rip_rpc_itf_Login_DoLogin_Prm EDict = 4
	EDict_rip_rpc_itf_Login_Test1_Prm   EDict = 5
)

var EDict_name = map[int32]string{
	0: "None",
	1: "base_Call",
	2: "rip_rpc_itf_Login_DoLogin_Ret",
	3: "rip_rpc_itf_Login_Test1_Ret",
	4: "rip_rpc_itf_Login_DoLogin_Prm",
	5: "rip_rpc_itf_Login_Test1_Prm",
}
var EDict_value = map[string]int32{
	"None":                          0,
	"base_Call":                     1,
	"rip_rpc_itf_Login_DoLogin_Ret": 2,
	"rip_rpc_itf_Login_Test1_Ret":   3,
	"rip_rpc_itf_Login_DoLogin_Prm": 4,
	"rip_rpc_itf_Login_Test1_Prm":   5,
}

func (x EDict) String() string {
	return proto.EnumName(EDict_name, int32(x))
}
func (EDict) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("dict.EDict", EDict_name, EDict_value)
}

func init() { proto.RegisterFile("dict.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xc9, 0x4c, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xb5, 0x56, 0x30, 0x72, 0xb1, 0xba,
	0xba, 0x64, 0x26, 0x97, 0x08, 0x71, 0x70, 0xb1, 0xf8, 0xe5, 0xe7, 0xa5, 0x0a, 0x30, 0x08, 0xf1,
	0x72, 0x71, 0x26, 0x25, 0x16, 0xa7, 0xc6, 0x3b, 0x27, 0xe6, 0xe4, 0x08, 0x30, 0x0a, 0x29, 0x72,
	0xc9, 0x16, 0x65, 0x16, 0xc4, 0x17, 0x15, 0x24, 0xc7, 0x67, 0x96, 0xa4, 0xc5, 0xfb, 0xe4, 0xa7,
	0x67, 0xe6, 0xc5, 0xbb, 0xe4, 0x43, 0xe8, 0xa0, 0xd4, 0x12, 0x01, 0x26, 0x21, 0x79, 0x2e, 0x69,
	0x4c, 0x25, 0x21, 0xa9, 0xc5, 0x25, 0x86, 0x60, 0x05, 0xcc, 0xf8, 0xcd, 0x08, 0x28, 0xca, 0x15,
	0x60, 0xc1, 0x67, 0x06, 0x48, 0x01, 0x6b, 0x12, 0x1b, 0xd8, 0xdd, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc2, 0xf0, 0xa6, 0x31, 0xc5, 0x00, 0x00, 0x00,
}
