// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smn_base.proto

#ifndef PROTOBUF_INCLUDED_smn_5fbase_2eproto
#define PROTOBUF_INCLUDED_smn_5fbase_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_smn_5fbase_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_smn_5fbase_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_smn_5fbase_2eproto();
namespace smn_base {
class Call;
class CallDefaultTypeInternal;
extern CallDefaultTypeInternal _Call_default_instance_;
class FPkg;
class FPkgDefaultTypeInternal;
extern FPkgDefaultTypeInternal _FPkg_default_instance_;
class Ret;
class RetDefaultTypeInternal;
extern RetDefaultTypeInternal _Ret_default_instance_;
}  // namespace smn_base
namespace google {
namespace protobuf {
template<> ::smn_base::Call* Arena::CreateMaybeMessage<::smn_base::Call>(Arena*);
template<> ::smn_base::FPkg* Arena::CreateMaybeMessage<::smn_base::FPkg>(Arena*);
template<> ::smn_base::Ret* Arena::CreateMaybeMessage<::smn_base::Ret>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace smn_base {

// ===================================================================

class Call : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:smn_base.Call) */ {
 public:
  Call();
  virtual ~Call();

  Call(const Call& from);

  inline Call& operator=(const Call& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Call(Call&& from) noexcept
    : Call() {
    *this = ::std::move(from);
  }

  inline Call& operator=(Call&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Call& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Call* internal_default_instance() {
    return reinterpret_cast<const Call*>(
               &_Call_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Call* other);
  friend void swap(Call& a, Call& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Call* New() const final {
    return CreateMaybeMessage<Call>(NULL);
  }

  Call* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Call>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Call& from);
  void MergeFrom(const Call& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Call* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const void* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // int32 dict = 1;
  void clear_dict();
  static const int kDictFieldNumber = 1;
  ::google::protobuf::int32 dict() const;
  void set_dict(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:smn_base.Call)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 dict_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_smn_5fbase_2eproto;
};
// -------------------------------------------------------------------

class Ret : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:smn_base.Ret) */ {
 public:
  Ret();
  virtual ~Ret();

  Ret(const Ret& from);

  inline Ret& operator=(const Ret& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Ret(Ret&& from) noexcept
    : Ret() {
    *this = ::std::move(from);
  }

  inline Ret& operator=(Ret&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Ret& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Ret* internal_default_instance() {
    return reinterpret_cast<const Ret*>(
               &_Ret_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Ret* other);
  friend void swap(Ret& a, Ret& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Ret* New() const final {
    return CreateMaybeMessage<Ret>(NULL);
  }

  Ret* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Ret>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Ret& from);
  void MergeFrom(const Ret& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ret* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes msg = 3;
  void clear_msg();
  static const int kMsgFieldNumber = 3;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const void* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // int32 dict = 1;
  void clear_dict();
  static const int kDictFieldNumber = 1;
  ::google::protobuf::int32 dict() const;
  void set_dict(::google::protobuf::int32 value);

  // bool Err = 2;
  void clear_err();
  static const int kErrFieldNumber = 2;
  bool err() const;
  void set_err(bool value);

  // @@protoc_insertion_point(class_scope:smn_base.Ret)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 dict_;
  bool err_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_smn_5fbase_2eproto;
};
// -------------------------------------------------------------------

class FPkg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:smn_base.FPkg) */ {
 public:
  FPkg();
  virtual ~FPkg();

  FPkg(const FPkg& from);

  inline FPkg& operator=(const FPkg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FPkg(FPkg&& from) noexcept
    : FPkg() {
    *this = ::std::move(from);
  }

  inline FPkg& operator=(FPkg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const FPkg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FPkg* internal_default_instance() {
    return reinterpret_cast<const FPkg*>(
               &_FPkg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(FPkg* other);
  friend void swap(FPkg& a, FPkg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FPkg* New() const final {
    return CreateMaybeMessage<FPkg>(NULL);
  }

  FPkg* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FPkg>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FPkg& from);
  void MergeFrom(const FPkg& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FPkg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const void* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // int64 NO = 1;
  void clear_no();
  static const int kNOFieldNumber = 1;
  ::google::protobuf::int64 no() const;
  void set_no(::google::protobuf::int64 value);

  // bool Err = 3;
  void clear_err();
  static const int kErrFieldNumber = 3;
  bool err() const;
  void set_err(bool value);

  // @@protoc_insertion_point(class_scope:smn_base.FPkg)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int64 no_;
  bool err_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_smn_5fbase_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Call

// int32 dict = 1;
inline void Call::clear_dict() {
  dict_ = 0;
}
inline ::google::protobuf::int32 Call::dict() const {
  // @@protoc_insertion_point(field_get:smn_base.Call.dict)
  return dict_;
}
inline void Call::set_dict(::google::protobuf::int32 value) {
  
  dict_ = value;
  // @@protoc_insertion_point(field_set:smn_base.Call.dict)
}

// bytes msg = 2;
inline void Call::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Call::msg() const {
  // @@protoc_insertion_point(field_get:smn_base.Call.msg)
  return msg_.GetNoArena();
}
inline void Call::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:smn_base.Call.msg)
}
#if LANG_CXX11
inline void Call::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:smn_base.Call.msg)
}
#endif
inline void Call::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:smn_base.Call.msg)
}
inline void Call::set_msg(const void* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:smn_base.Call.msg)
}
inline ::std::string* Call::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:smn_base.Call.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Call::release_msg() {
  // @@protoc_insertion_point(field_release:smn_base.Call.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Call::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:smn_base.Call.msg)
}

// -------------------------------------------------------------------

// Ret

// int32 dict = 1;
inline void Ret::clear_dict() {
  dict_ = 0;
}
inline ::google::protobuf::int32 Ret::dict() const {
  // @@protoc_insertion_point(field_get:smn_base.Ret.dict)
  return dict_;
}
inline void Ret::set_dict(::google::protobuf::int32 value) {
  
  dict_ = value;
  // @@protoc_insertion_point(field_set:smn_base.Ret.dict)
}

// bool Err = 2;
inline void Ret::clear_err() {
  err_ = false;
}
inline bool Ret::err() const {
  // @@protoc_insertion_point(field_get:smn_base.Ret.Err)
  return err_;
}
inline void Ret::set_err(bool value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:smn_base.Ret.Err)
}

// bytes msg = 3;
inline void Ret::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Ret::msg() const {
  // @@protoc_insertion_point(field_get:smn_base.Ret.msg)
  return msg_.GetNoArena();
}
inline void Ret::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:smn_base.Ret.msg)
}
#if LANG_CXX11
inline void Ret::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:smn_base.Ret.msg)
}
#endif
inline void Ret::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:smn_base.Ret.msg)
}
inline void Ret::set_msg(const void* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:smn_base.Ret.msg)
}
inline ::std::string* Ret::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:smn_base.Ret.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Ret::release_msg() {
  // @@protoc_insertion_point(field_release:smn_base.Ret.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Ret::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:smn_base.Ret.msg)
}

// -------------------------------------------------------------------

// FPkg

// int64 NO = 1;
inline void FPkg::clear_no() {
  no_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 FPkg::no() const {
  // @@protoc_insertion_point(field_get:smn_base.FPkg.NO)
  return no_;
}
inline void FPkg::set_no(::google::protobuf::int64 value) {
  
  no_ = value;
  // @@protoc_insertion_point(field_set:smn_base.FPkg.NO)
}

// bytes msg = 2;
inline void FPkg::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& FPkg::msg() const {
  // @@protoc_insertion_point(field_get:smn_base.FPkg.msg)
  return msg_.GetNoArena();
}
inline void FPkg::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:smn_base.FPkg.msg)
}
#if LANG_CXX11
inline void FPkg::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:smn_base.FPkg.msg)
}
#endif
inline void FPkg::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:smn_base.FPkg.msg)
}
inline void FPkg::set_msg(const void* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:smn_base.FPkg.msg)
}
inline ::std::string* FPkg::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:smn_base.FPkg.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* FPkg::release_msg() {
  // @@protoc_insertion_point(field_release:smn_base.FPkg.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void FPkg::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:smn_base.FPkg.msg)
}

// bool Err = 3;
inline void FPkg::clear_err() {
  err_ = false;
}
inline bool FPkg::err() const {
  // @@protoc_insertion_point(field_get:smn_base.FPkg.Err)
  return err_;
}
inline void FPkg::set_err(bool value) {
  
  err_ = value;
  // @@protoc_insertion_point(field_set:smn_base.FPkg.Err)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace smn_base

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_smn_5fbase_2eproto
