// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smn_base/smn_base.proto

package smn_base

import (
	fmt "fmt"
	smn_dict "github.com/ProtossGenius/SureMoonNet/pb/smn_dict"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Call struct {
	Dict                 smn_dict.EDict `protobuf:"varint,1,opt,name=dict,proto3,enum=smn_dict.EDict" json:"dict,omitempty"`
	Msg                  []byte         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_b00eef6af23f64b0, []int{0}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetDict() smn_dict.EDict {
	if m != nil {
		return m.Dict
	}
	return smn_dict.EDict_None
}

func (m *Call) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Ret struct {
	Dict                 smn_dict.EDict `protobuf:"varint,1,opt,name=dict,proto3,enum=smn_dict.EDict" json:"dict,omitempty"`
	Err                  bool           `protobuf:"varint,2,opt,name=Err,proto3" json:"Err,omitempty"`
	Msg                  []byte         `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Ret) Reset()         { *m = Ret{} }
func (m *Ret) String() string { return proto.CompactTextString(m) }
func (*Ret) ProtoMessage()    {}
func (*Ret) Descriptor() ([]byte, []int) {
	return fileDescriptor_b00eef6af23f64b0, []int{1}
}

func (m *Ret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ret.Unmarshal(m, b)
}
func (m *Ret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ret.Marshal(b, m, deterministic)
}
func (m *Ret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ret.Merge(m, src)
}
func (m *Ret) XXX_Size() int {
	return xxx_messageInfo_Ret.Size(m)
}
func (m *Ret) XXX_DiscardUnknown() {
	xxx_messageInfo_Ret.DiscardUnknown(m)
}

var xxx_messageInfo_Ret proto.InternalMessageInfo

func (m *Ret) GetDict() smn_dict.EDict {
	if m != nil {
		return m.Dict
	}
	return smn_dict.EDict_None
}

func (m *Ret) GetErr() bool {
	if m != nil {
		return m.Err
	}
	return false
}

func (m *Ret) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type FPkg struct {
	NO                   int64    `protobuf:"varint,1,opt,name=NO,proto3" json:"NO,omitempty"`
	Msg                  []byte   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Err                  bool     `protobuf:"varint,3,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FPkg) Reset()         { *m = FPkg{} }
func (m *FPkg) String() string { return proto.CompactTextString(m) }
func (*FPkg) ProtoMessage()    {}
func (*FPkg) Descriptor() ([]byte, []int) {
	return fileDescriptor_b00eef6af23f64b0, []int{2}
}

func (m *FPkg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FPkg.Unmarshal(m, b)
}
func (m *FPkg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FPkg.Marshal(b, m, deterministic)
}
func (m *FPkg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FPkg.Merge(m, src)
}
func (m *FPkg) XXX_Size() int {
	return xxx_messageInfo_FPkg.Size(m)
}
func (m *FPkg) XXX_DiscardUnknown() {
	xxx_messageInfo_FPkg.DiscardUnknown(m)
}

var xxx_messageInfo_FPkg proto.InternalMessageInfo

func (m *FPkg) GetNO() int64 {
	if m != nil {
		return m.NO
	}
	return 0
}

func (m *FPkg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *FPkg) GetErr() bool {
	if m != nil {
		return m.Err
	}
	return false
}

func init() {
	proto.RegisterType((*Call)(nil), "smn_base.Call")
	proto.RegisterType((*Ret)(nil), "smn_base.Ret")
	proto.RegisterType((*FPkg)(nil), "smn_base.FPkg")
}

func init() { proto.RegisterFile("smn_base/smn_base.proto", fileDescriptor_b00eef6af23f64b0) }

var fileDescriptor_b00eef6af23f64b0 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0xce, 0xcd, 0x8b,
	0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0x87, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60,
	0x7c, 0x29, 0xfb, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0x00, 0x90,
	0x5c, 0x71, 0xb1, 0x7b, 0x6a, 0x5e, 0x66, 0x69, 0xb1, 0x7e, 0x70, 0x69, 0x51, 0xaa, 0x6f, 0x7e,
	0x7e, 0x9e, 0x5f, 0x6a, 0x89, 0x7e, 0x41, 0x12, 0xd8, 0x84, 0x94, 0xcc, 0xe4, 0x12, 0x38, 0x03,
	0x62, 0x94, 0x92, 0x2d, 0x17, 0x8b, 0x73, 0x62, 0x4e, 0x8e, 0x90, 0x32, 0x17, 0x0b, 0x48, 0x54,
	0x82, 0x51, 0x81, 0x51, 0x83, 0xcf, 0x88, 0x5f, 0x0f, 0xae, 0xcc, 0xd5, 0x25, 0x33, 0xb9, 0x24,
	0x08, 0x2c, 0x29, 0x24, 0xc0, 0xc5, 0x9c, 0x5b, 0x9c, 0x2e, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x13,
	0x04, 0x62, 0x2a, 0xf9, 0x71, 0x31, 0x07, 0xa5, 0x96, 0x10, 0xad, 0xdb, 0xb5, 0xa8, 0x08, 0xac,
	0x9b, 0x23, 0x08, 0xc4, 0x84, 0x99, 0xc7, 0x8c, 0x30, 0xcf, 0x8a, 0x8b, 0xc5, 0x2d, 0x20, 0x3b,
	0x5d, 0x88, 0x8f, 0x8b, 0xc9, 0xcf, 0x1f, 0x6c, 0x1c, 0x73, 0x10, 0x93, 0x9f, 0x3f, 0xa6, 0xcd,
	0x30, 0xd3, 0x98, 0xe1, 0xa6, 0x25, 0xb1, 0x81, 0x7d, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xec, 0x50, 0x46, 0x30, 0x37, 0x01, 0x00, 0x00,
}
